.PHONEY: gen_markdown
gen_markdown:
	../.build/release/MarkdownFileCreator --sourcefile sample.yml --keys id,name,gender,params --verbose true

.PHONEY: gen_markdown_2
gen_markdown_2:
	../.build/release/MarkdownFileCreator --sourcefile sample2.yaml --keys widget.debug,widget.image,widget.text --verbose true